/*TABLES CREATION*/
CREATE TABLE IF NOT EXISTS Users(
"id VARCHAR(10) NOT NULL, firstname VARCHAR(20) NOT NULL,  last name VARCHAR(20) NOT NULL, username VARCHAR(20) NOT NULL, password PASSWORD DOUBLE NOT NULL, Currency CHAR) ENGINE = InnoDB;")